enigmatic_oro_marketing_mailing_home:
    pattern:  /marketing/mailing
    defaults: { _controller: EnigmaticOROMailingBundle:Campaign:index }

enigmatic_oro_marketing_mailing_view:
    pattern:  /marketing/mailing/{campaign}
    defaults: { _controller: EnigmaticOROMailingBundle:Campaign:view }
    requirements:
        campaign: \d+

enigmatic_oro_marketing_mailing_add:
    pattern:  /marketing/mailing/ajouter
    defaults: { _controller: EnigmaticOROMailingBundle:Campaign:add }

enigmatic_oro_marketing_mailing_update:
    pattern:  /marketing/mailing/modifier-{campaign}
    defaults: { _controller: EnigmaticOROMailingBundle:Campaign:update }
    requirements:
        campaign: \d+

enigmatic_oro_marketing_mailing_remove:
    pattern:  /marketing/mailing/supprimer-{campaign}
    defaults: { _controller: EnigmaticOROMailingBundle:Campaign:remove }
    requirements:
        campaign: \d+

enigmatic_oro_marketing_mailing_contact_search:
    pattern:  /marketing/mailing/contact_search
    defaults: { _controller: EnigmaticOROMailingBundle:Campaign:searchContact }