services:
# FORM
    enigmatic_crm.form.agency:
        class: Enigmatic\CRMBundle\Form\AgencyType
        tags:
            - { name: form.type, alias: enigmatic_crm_agency }
        arguments: [@enigmatic_city.transformer.default]

