enigmatic_crm:
    resource: "@EnigmaticCRMBundle/Resources/config/routing.yml"
    prefix:   /

enigmatic_city:
    resource: "@EnigmaticCityBundle/Resources/config/routing.yml"
    prefix:   /villes

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
