parameters:
    email.super_admin:  %email_super_admin%
    email.admin:        %email_admin%
    email.error:        %email_error%
    email.sender:       %email_sender%
    email.from:         %email_from%

services:
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }
