parameters:
    email.super_admin:  %email_super_admin%
    email.admin:        %email_admin%
    email.error:        %email_error%
    email.sender:       %email_sender%
    email.from:         %email_from%

services:
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }

    enigmatic.render:
        class: AppBundle\Services\Render
        arguments: [@service_container]

    enigmatic.crypt_mail:
        class: AppBundle\Services\CryptEmail
        tags:
            -  { name: twig.extension }

    enigmatic.phone_format:
        class: AppBundle\Services\PhoneFormat
        tags:
            -  { name: twig.extension }

    enigmatic.rewrite_to_url:
        class: AppBundle\Services\RewriteToUrl
        tags:
            -  { name: twig.extension }

    enigmatic.token_generator:
        class: AppBundle\Services\TokenGenerator
        tags:
            -  { name: twig.extension }

    enigmatic_mailer.transport.spool:
        class: Enigmatic\MailerBundle\Model\Transport
        arguments: [@swiftmailer.mailer.spooled, %enigmatic_mailer.email_from%, 'Enigmatic (spool)']
        tags:
            -  { name: enigmatic_mailer.transport, alias: spool }