<?php

namespace Enigmatic\CRMBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AgencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgencyRepository extends EntityRepository
{
    public function getList($page = 0, $listPageLimit = null, $params = array()) {

        $qb = $this->createQueryBuilder('agency');

        $qb = $this->join($qb, true);
        if (isset($params['search']))
            $qb = $this->search($qb, $params['search']);
        if (isset($params['order']))
            $qb = $this->order($qb, $params['order']);

        $qb ->getQuery();

        if ($listPageLimit) {
            $qb ->setFirstResult($page * $listPageLimit)
                ->setMaxResults($listPageLimit);
        }

        return new Paginator($qb);
    }

    public function find($id) {

        $qb = $this->createQueryBuilder('agency');
        $qb = $this->join($qb, true);
        $qb ->where('agency = :id')
            ->setParameter('id', $id);

        return $qb->getQuery()->getOneOrNullResult();
    }

    public function findAll() {

        $qb = $this->createQueryBuilder('agency');
        $qb = $this->join($qb, true);

        return $qb->getQuery()->getResult();
    }

    protected function join(QueryBuilder $qb, $add = false)
    {
        $qb->leftjoin('agency.accounts', 'accounts');
        $qb->leftjoin('agency.users', 'users');
        $qb->leftjoin('users.end', 'users_end');
        $qb->leftjoin('agency.contacts', 'contacts');
        $qb->leftjoin('agency.city', 'city');

        if ($add) {
            $qb->addSelect('accounts');
            $qb->addSelect('users');
            $qb->addSelect('users_end');
            $qb->addSelect('contacts');
            $qb->addSelect('city');
        }

        return $qb;
    }

    protected function search(QueryBuilder $qb, $searchs)
    {
        if (is_array($searchs)) {
            foreach ($searchs as $field => $value) {
                if ($value) {
                    switch ($field) {
                        case 'id':
                            $qb ->andWhere('agency.id = :search_id');
                            $qb ->setParameter('search_id', $value);
                            break;
                        case 'name':
                            $qb ->andWhere('agency.name LIKE :search_name');
                            $qb ->setParameter('search_name', '%'.$value.'%');
                            break;
                        case 'address_full':
                            $qb ->andWhere('agency.address LIKE :search_address_full OR agency.addressCpl LIKE :search_address_full OR city.canonicalName LIKE :search_address_full OR city.zipcode LIKE :search_address_full');
                            $qb ->setParameter('search_address_full', '%'.$value.'%');
                            break;
                    }
                }
            }
        }

        return $qb;
    }

    protected function order(QueryBuilder $qb, $orders = null)
    {
        if (is_array($orders)) {
            foreach ($orders as $field => $direction) {
                if ($direction != 'ASC')
                    $direction = 'DESC';
                switch ($field) {
                    case 'id':
                        $qb ->addOrderBy('agency.id', $direction);
                        break;
                    case 'name':
                        $qb ->addOrderBy('agency.name', $direction);
                        break;
                }
            }
        }

        return $qb;
    }
}
