oro_menu_config:
    items:
        marketing_tab:
            label: 'orocrm.campaign.menu.marketing_tab.label'
            uri:   '#'
            extras:
                position: 300
        enigmatic_oro_marketing_faxing_link:
            label: Faxing
            route: enigmatic_oro_marketing_faxing_home
            extras:
                routes: ['/^enigmatic_oro_marketing_faxing_home/']
                description: Faxing
    tree:
        application_menu:
            children:
                marketing_tab:
                    children:
                        enigmatic_oro_marketing_faxing_link: ~

oro_titles:
    enigmatic_oro_marketing_faxing_home: Faxing