enigmatic_crm_account_owner_add:
    locales:  { fr: "/ajouter-{account}", en: "/add-{account}" }
    defaults: { _controller: EnigmaticCRMBundle:AccountOwner:add, first: false }
    requirements:
        account: \d+

enigmatic_crm_account_owner_add_first:
    locales:  { fr: "/lien-{account}", en: "/link-{account}" }
    defaults: { _controller: EnigmaticCRMBundle:AccountOwner:add, first: true }
    requirements:
        account: \d+

enigmatic_crm_account_owner_remove:
    locales:  { fr: "/supprimer-{account_owner}", en: "/remove-{account_owner}" }
    defaults: { _controller: EnigmaticCRMBundle:AccountOwner:remove }
    requirements:
        account_owner: \d+