enigmatic_oro_marketing_faxing_home:
    pattern:  /marketing/faxing
    defaults: { _controller: EnigmaticOROFaxingBundle:Campaign:index }

enigmatic_oro_marketing_faxing_view:
    pattern:  /marketing/faxing/{campaign}
    defaults: { _controller: EnigmaticOROFaxingBundle:Campaign:view }
    requirements:
        campaign: \d+

enigmatic_oro_marketing_faxing_add:
    pattern:  /marketing/faxing/ajouter
    defaults: { _controller: EnigmaticOROFaxingBundle:Campaign:add }

enigmatic_oro_marketing_faxing_update:
    pattern:  /marketing/faxing/modifier-{campaign}
    defaults: { _controller: EnigmaticOROFaxingBundle:Campaign:update }
    requirements:
        campaign: \d+

enigmatic_oro_marketing_faxing_remove:
    pattern:  /marketing/faxing/supprimer-{campaign}
    defaults: { _controller: EnigmaticOROFaxingBundle:Campaign:remove }
    requirements:
        campaign: \d+

enigmatic_oro_marketing_faxing_contact_search:
    pattern:  /marketing/faxing/contact_search
    defaults: { _controller: EnigmaticOROFaxingBundle:Campaign:searchContact }

enigmatic_oro_marketing_faxing_download_fax:
    pattern:  /marketing/faxing/télécharger-fax-{campaign_fax}
    defaults: { _controller: EnigmaticOROFaxingBundle:Campaign:downloadFax }
    requirements:
        campaign_fax: \d+