services:
    enigmatic_mailer.transport.spool:
        class: Enigmatic\MailerBundle\Model\Transport
        arguments: [@swiftmailer.mailer.mailing, %enigmatic_mailer.email_from%, 'Spooool']
        tags:
            -  { name: enigmatic_mailer.transport, alias: spool }